# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      - rc-**

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Run black to review standard code format
      run: |
        # Checks if need to reformat files
        black --check --diff .
    - name: Run flake8 to check specific rules not covered by black
      run: |
        # Checks syntax and undefined names errors
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Checks code complexity, exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10  --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Build coverage file
      run: |
        pytest --cache-clear --cov=app test/ > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2

    - name: pytest-coverage-commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt